BookMyDoc/BookMyDoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('patient/', include('patient.urls')),
    path('hospital/', include('hospital.urls')),
    path('doctor/', include('doctor.urls')),
    path('', RedirectView.as_view(url='user/')),
    path('', include('django.contrib.auth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BookMyDoc/doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'
urlpatterns = [
    path('index', views.index, name="index"),
    path('dashboard', views.DoctorDashboardView.as_view(), name="dashboard"),
    path('doc_profile/<int:pk>', views.DoctorProfileView.as_view(), name="doc_profile"),
    path('doc_qualification', views.QualificationView.as_view(), name="doc_qualification"),
    path('delete_doc_qualification/<int:pk>', views.DeleteDocQualification.as_view(), name="delete_doc_qualification"),
    path('edit_doc_qualification/<int:pk>', views.EditDocQualification.as_view(), name="edit_doc_qualification"),
    path('doc_time_slot', views.DocTimeSlotView.as_view(), name="doc_time_slot"),
    path('edit_doc_time_slot/<int:pk>', views.EditDocTimeSlot.as_view(), name="edit_doc_time_slot"),
    path('delete_doc_time_slot/<int:pk>', views.DeleteDocTimeSlot.as_view(), name="delete_doc_time_slot"),
    path('today_appointments', views.TodayAppointments.as_view(), name="today_appointments"),
    path('cancel_today_appointments/<int:pk>', views.CancelTodayAppointments.as_view(), name="cancel_today_appointments"),
    path('change_appointment_status', views.ChangeAppointmentStatus.as_view(), name="change_appointment_status"),
    path('check_status', views.CheckStatus.as_view(), name="check_status"),
    path('all_appointments', views.AllAppointments.as_view(), name="all_appointments"),
    path('cancel_appointments/<int:pk>', views.CancelAppointments.as_view(), name="cancel_appointments"),
    path('patient_medical_history/<int:pk>', views.PatientMedicalHistory.as_view(), name="patient_medical_history"),
    path('all_hospital', views.AllHospitalView.as_view(), name="all_hospital"),
    path('doctor_list_view/<int:pk>', views.DoctorListView.as_view(), name="doctor_list_view"),
    path('other_appointments', views.OtherAppointmentView.as_view(), name="other_appointments"),
    path('status_filter', views.StatusFilter.as_view(), name="status_filter"),
    path('show_checkup_timing', views.ShowCheckupTiming.as_view(), name="show_checkup_timing")



]

BookMyDoc/hospital/urls.py
from django.urls import path
from . import views
from .views import HospitalProfile

app_name = "hospital"
urlpatterns = [
    path('index', views.index, name="index"),
    path('hospital_dashboard', views.HospitalDashboard.as_view(), name="hospital_dashboard"),
    path('hospital_request', views.HospitalClinicRequest.as_view(), name="hospital_request"),
    path('hospital_profile/<int:pk>', HospitalProfile.as_view(), name="hospital_profile"),
    path('add_doctor', views.AddDoctor.as_view(), name="add_doctor"),
    path('doc_list', views.AllDoctorListView.as_view(), name="doc_list"),
    path('appointment_slot/<int:pk>', views.AppointmentTimeSlotView.as_view(), name="appointment_slot"),
    path('appointment_book', views.AppointmentBookView.as_view(), name="appointment_book"),
    path('upload_hospital_images', views.UploadHospitalImages.as_view(), name="upload_hospital_images"),
    path('all_hospital_images', views.AllHospitalImages.as_view(), name="all_hospital_images"),
    path('hospital_delete_image/<int:pk>', views.HospitalDeleteImage.as_view(), name="hospital_delete_image"),
    path('all_doctor_list', views.AllDocList.as_view(), name="all_doctor_list"),
    path('delete_doc/<int:pk>', views.DeleteDoc.as_view() , name="delete_doc")

]

BookMyDoc/patient/urls.py
from django.urls import path
from . import views
from .views import UserProfile, PatientMedicalHistory
app_name = 'patient'
urlpatterns = [
    path('index', views.index, name="index"),
    path('wrong', views.write, name="wrong"),
    path('user_profile/<int:pk>', UserProfile.as_view(), name="user_profile"),
    path('patient_medical_history', PatientMedicalHistory.as_view(), name="patient_medical_history"),
    path('all_hospital', views.DisplayHospital.as_view(), name="all_hospital"),
    path('hospital_detail/<int:pk>/', views.HospitalDetailView.as_view(), name="hospital_detail"),
    path('booking/<int:pk>', views.BookingView.as_view(), name="booking"),
    path('time_slot', views.AppointmentBooking.as_view(), name="time_slot"),
    path('my_appointments', views.MyAppointmentsView.as_view(), name="my_appointments"),
    path('cancel_appointments/<int:pk>', views.CancelAppointments.as_view(), name="cancel_appointments"),
]

BookMyDoc/user/urls.py
from django.urls import path, include
from . import views
from .views import RegisterView, LoginView
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('about_us', views.AboutUsView.as_view(), name="about_us"),
    path('contact', views.ContactView.as_view(), name="contact"),
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('login_mixin', views.LoginMixin, name="login_mixin"),
    path('logout/', views.logout_view, name="logout"),
    path('index_login', views.index_login, name="index_login"),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('%5reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

BookMyDoc/templates/partials/footer.html
{% load static %}
    	<!-- Footer -->

	<footer class="footer">
<!--		<div class="parallax_background parallax-window" data-parallax="scroll" style="background_image:url({% static 'images/footer.jpg'%});" data-speed="0.8"></div>-->
<!--        <div class="background_image" style="background-image:url({% static 'images/footer.jpg' %});">-->
<!--        </div>-->

<!--		<div class="footer_content">-->
<!--			<div class="container">-->
<!--				<div class="row">-->

					<!-- Footer About -->
<!--					<div class="col-lg-3 footer_col">-->
<!--						<div class="footer_about">-->
<!--							<div class="logo">-->
<!--								<a href="#">health<span>+</span></a>-->
<!--							</div>-->
<!--							<div class="footer_about_text">Lorem ipsum dolor sit amet, lorem maximus consectetur adipiscing elit. Donec malesuada lorem maximus mauris.</div>-->
<!--							<div class="footer_social">-->
<!--								<ul class="d-flex flex-row align-items-center justify-content-start">-->
<!--									<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>-->
<!--									<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>-->
<!--									<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>-->
<!--									<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>-->
<!--									<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>-->
<!--									<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>-->
<!--								</ul>-->
<!--							</div>-->
<!--							<div class="copyright">&lt;!&ndash; Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. &ndash;&gt;-->
<!--Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>-->
<!--&lt;!&ndash; Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. &ndash;&gt;-->
<!--</div>-->
<!--						</div>-->
<!--					</div>-->

					<!-- Footer Contact -->
<!--					<div class="col-lg-5 footer_col">-->
<!--						<div class="footer_contact">-->
<!--							<div class="footer_contact_title">Quick Contact</div>-->
<!--							<div class="footer_contact_form_container">-->
<!--								<form action="#" class="footer_contact_form" id="footer_contact_form">-->
<!--									<div class="d-flex flex-xl-row flex-column align-items-center justify-content-between">-->
<!--										<input type="text" class="footer_contact_input" placeholder="Name" required="required">-->
<!--										<input type="email" class="footer_contact_input" placeholder="E-mail" required="required">-->
<!--									</div>-->
<!--									<textarea class="footer_contact_input footer_contact_textarea" placeholder="Message" required="required"></textarea>-->
<!--									<button class="footer_contact_button">send message</button>-->
<!--								</form>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->

					<!-- Footer Hours -->
<!--					<div class="col-lg-4 footer_col">-->
<!--						<div class="footer_hours">-->
<!--							<div class="footer_hours_title">Opening Hours</div>-->
<!--							<ul class="hours_list">-->
<!--								<li class="d-flex flex-row align-items-center justify-content-start">-->
<!--									<div>Monday – Thursday</div>-->
<!--									<div class="ml-auto">8.00 – 19.00</div>-->
<!--								</li>-->
<!--								<li class="d-flex flex-row align-items-center justify-content-start">-->
<!--									<div>Friday</div>-->
<!--									<div class="ml-auto">8.00 - 18.30</div>-->
<!--								</li>-->
<!--								<li class="d-flex flex-row align-items-center justify-content-start">-->
<!--									<div>Saturday</div>-->
<!--									<div class="ml-auto">9.30 – 17.00</div>-->
<!--								</li>-->
<!--								<li class="d-flex flex-row align-items-center justify-content-start">-->
<!--									<div>Sunday</div>-->
<!--									<div class="ml-auto">9.30 – 15.00</div>-->
<!--								</li>-->
<!--							</ul>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
		<div class="footer_bar">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="footer_bar_content d-flex flex-sm-row flex-column align-items-lg-center align-items-start justify-content-start">
							<nav class="footer_nav">
								<ul class="d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start">
										<li class="active"><a href="{% url 'user:index'%}">Home</a></li>
										<li><a href="{% url 'user:about_us' %}">About Us</a></li>
<!--									<li><a href="services.html">Services</a></li>-->
<!--									<li><a href="news.html">News</a></li>-->
									<li><a href="{% url 'user:contact' %}">Contact</a></li>
								</ul>
							</nav>
							<div class="footer_links">
								<ul class="d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start">
<!--									<li class="active"><a href="{% url 'user:index'%}">Home</a></li>-->
<!--									<li><a href="about.html">About Us</a></li>-->
<!--									<li><a href="#">Help Desk</a></li>-->
<!--									<li><a href="#">Emergency Services</a></li>-->
<!--									<li><a href="#">Appointment</a></li>-->
								</ul>
							</div>
							<div class="footer_phone ml-lg-auto">
								<i class="fa fa-phone" aria-hidden="true"></i>
								<span>+8758162943</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

BookMyDoc/templates/partials/header.html
{% load static %}
<div class="super_container">

    <!-- Menu -->

    <div class="menu trans_500">
        <div class="menu_content d-flex flex-column align-items-center justify-content-center text-center">
            <div class="menu_close_container">
                <div class="menu_close"></div>
            </div>
            <form action="#" class="menu_search_form">
                <input type="text" class="menu_search_input" placeholder="Search" required="required">
                <button class="menu_search_button"><i class="fa fa-search" aria-hidden="true"></i></button>
            </form>
            <ul>
                <li class="active"><a href="{% url 'user:index'%}">Home</a></li>
                <li><a href="{% url 'user:about_us' %}">About us</a></li>
                <li><a href="{% url 'user:contact' %}">Contact</a></li>
                <li><a href="{% url 'patient:all_hospital' %}">all hospital</a></li>
            </ul>
        </div>
        <div class="menu_social">
            <ul>
                <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            </ul>
        </div>
    </div>
    <!-- Home -->

    <div class="home" style="height: auto;">
        <!--		<div class="background_image" style="background-image:url({% static 'images/index_hero.jpg' %})"></div>-->

        <!-- Header -->


        <div class="header_top">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="header_top_content d-flex flex-row align-items-center justify-content-start">
                            <div class="logo">
                                <a href="{% url 'user:index'%}">bookmydoc<span>+</span></a>
                            </div>
                            <div class="header_top_extra d-flex flex-row align-items-center justify-content-start ml-auto">
                                <div class="header_top_nav">
                                    <ul class="d-flex flex-row align-items-center justify-content-start">
                                        {% if request.user.is_authenticated %}
                                        <li>hello {{request.user}}</li>
                                        <li><a href="{% url 'user:logout'%}">Logout</a></li>
                                        {% else %}
                                        <li><a id="login-form" style="cursor:pointer;">Login</a></li>
                                        <li><a id="register-form" style="cursor:pointer;">Sign up</a></li>
                                        {% endif %}
                                        <!--												<li><a href="#">Help Desk</a></li>-->
                                        <!--												<li><a href="#">Emergency Services</a></li>-->
                                        <!--												<li><a href="#">Appointment</a></li>-->
                                    </ul>
                                </div>
                                <div class="header_top_phone">
                                    <i class="fa fa-phone" aria-hidden="true"></i>
                                    <span>+8758162943</span>
                                </div>
                            </div>
                            <div class="hamburger ml-auto"><i class="fa fa-bars" aria-hidden="true"></i></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header_nav" id="header_nav_pin">
            <div class="header_nav_inner">
                <div class="header_nav_container">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <div class="header_nav_content d-flex flex-row align-items-center justify-content-start">
                                    <nav class="main_nav">
                                        <ul class="d-flex flex-row align-items-center justify-content-start">
                                            {% if request.user.is_authenticated %}

                                            {% if user.is_type == "patient" %}
                                            <li class="active"><a href="{% url 'user:index'%}">Home</a></li>
                                            <li><a href="{% url 'patient:user_profile' request.user.id%}">User
                                                profile</a></li>
                                            <li><a href="{% url 'patient:patient_medical_history' %}">medical
                                                history</a></li>
                                            <li><a href="{% url 'patient:my_appointments' %}">my appointments</a></li>
                                            <li><a href="{% url 'patient:all_hospital' %}">all hospital</a></li>

                                            {% elif user.is_type == "doctor" %}
                                            <li class="active"><a href="{% url 'doctor:dashboard' %}">Dashboard</a></li>
                                            <!--                                                    <li class="active"><a href="{% url 'user:index'%}">Home</a></li>-->
                                            <!--                                                    <li>-->
                                            <!--                                                        <a href="{% url 'doctor:doc_profile' request.user.id %}">Profile</a>-->
                                            <!--                                                    </li>-->
                                            <!--                                                    <li><a href="{% url 'doctor:doc_qualification' %}">qualification</a>-->
                                            <!--                                                    </li>-->
                                            <!--                                                    <li><a href="{% url 'doctor:doc_time_slot' %}">Addtimeslot</a></li>-->

                                            {% elif user.is_type == "hospital" %}
                                            <!--                                                    <li class="active"><a href="{% url 'user:index'%}">Home</a></li>-->
                                            <li class="active"><a href="{% url 'hospital:hospital_dashboard'%}">Dashboard</a>
                                            </li>
                                            <!--                                                    <li><a href="{% url 'hospital:hospital_profile' request.user.id %}">profile</a>-->
                                            <!--                                                    </li>-->
                                            <!--                                                    <li><a href="{% url 'hospital:doc_list' %}">Doctor list </a></li>-->
                                            <!--                                                    <li><a href="{% url 'hospital:add_doctor' %}">add doctor</a></li>-->
                                            {% else %}
                                            <li class="active"><a href="{% url 'user:index'%}">Home</a></li>
                                            {% endif %}
                                            {% else %}
                                            <li class="active"><a href="{% url 'user:index'%}">Home</a></li>
                                            <li><a href="{% url 'user:about_us' %}">About us</a></li>
                                            <li><a href="{% url 'user:contact' %}">Contact</a></li>
                                            <li><a href="{% url 'patient:all_hospital' %}">all hospital</a></li>

                                            <!--													<li><a href="about.html">About Us</a></li>-->
                                            <!--													<li><a href="services.html">Services</a></li>-->
                                            <!--													<li><a href="news.html">News</a></li>-->
                                            <!--													<li><a href="contact.html">Contact</a></li>-->
                                            {% endif %}
                                        </ul>
                                    </nav>
                                    <!--                                            <div class="search_content d-flex flex-row align-items-center justify-content-end ml-auto">-->
                                    <!--                                                <form action="#" id="search_container_form"-->
                                    <!--                                                      class="search_container_form">-->
                                    <!--                                                    <input type="text" class="search_container_input"-->
                                    <!--                                                           placeholder="Search" required="required">-->
                                    <!--                                                    <button class="search_container_button"><i class="fa fa-search"-->
                                    <!--                                                                                               aria-hidden="true"></i>-->
                                    <!--                                                    </button>-->
                                    <!--                                                </form>-->
                                    <!--                                            </div>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

BookMyDoc/templates/partials/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>{{ message }}</strong>
</div>
{% endfor %}
{% endif %}