BookMyDoc/BookMyDoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('patient/', include('patient.urls')),
    path('hospital/', include('hospital.urls')),
    path('doctor/', include('doctor.urls')),
    path('', RedirectView.as_view(url='user/')),
    path('', include('django.contrib.auth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BookMyDoc/hospital/urls.py
from django.urls import path
from . import views
from .views import HospitalProfile

app_name = "hospital"
urlpatterns = [
    path('index', views.index, name="index"),
    path('hospital_dashboard', views.HospitalDashboard.as_view(), name="hospital_dashboard"),
    path('hospital_request', views.HospitalClinicRequest.as_view(), name="hospital_request"),
    path('hospital_profile/<int:pk>', HospitalProfile.as_view(), name="hospital_profile"),
    path('add_doctor', views.AddDoctor.as_view(), name="add_doctor"),
    path('doc_list', views.AllDoctorListView.as_view(), name="doc_list"),
    path('appointment_slot/<int:pk>', views.AppointmentTimeSlotView.as_view(), name="appointment_slot"),
    path('appointment_book', views.AppointmentBookView.as_view(), name="appointment_book"),
    path('upload_hospital_images', views.UploadHospitalImages.as_view(), name="upload_hospital_images"),
    path('all_hospital_images', views.AllHospitalImages.as_view(), name="all_hospital_images"),
    path('hospital_delete_image/<int:pk>', views.HospitalDeleteImage.as_view(), name="hospital_delete_image"),
    path('all_doctor_list', views.AllDocList.as_view(), name="all_doctor_list"),
    path('delete_doc/<int:pk>', views.DeleteDoc.as_view() , name="delete_doc")

]

BookMyDoc/user/urls.py
from django.urls import path, include
from . import views
from .views import RegisterView, LoginView
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('about_us', views.AboutUsView.as_view(), name="about_us"),
    path('contact', views.ContactView.as_view(), name="contact"),
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('login_mixin', views.LoginMixin, name="login_mixin"),
    path('logout/', views.logout_view, name="logout"),
    path('index_login', views.index_login, name="index_login"),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('%5reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

BookMyDoc/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime


# Create your models here.

class User(AbstractUser):
    STATUS = (
        ('patient', 'Patient'),
        ('doctor', 'Doctor'),
        ('hospital', 'Hospital'),
    )

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    is_type = models.CharField(max_length=10, choices=STATUS, default='patient')
    mobile_number = models.CharField(max_length=12)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    profile_image = models.ImageField(upload_to='images')


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=300)
    message = models.CharField(max_length=700)
    created_date = models.DateField()


class Carousel(models.Model):
    image = models.ImageField(upload_to='images')

BookMyDoc/user/forms.py
import re
from django import forms
from .models import User, Contact
from django.core.validators import validate_email
from django.core.exceptions import ValidationError


class RegisterForm(forms.ModelForm):
    first_name = forms.CharField(required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'enter your first name'}))
    last_name = forms.CharField(required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'enter your last name'}))
    username = forms.CharField(required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'enter your username'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'enter your email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'enter your password'}))

    mobile_number = forms.CharField(required=True,
                                    widget=forms.TextInput(attrs={'placeholder': 'enter your mobile number'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password', 'mobile_number']
        help_texts = {
            'username': None
        }

    def save(self, commit=True, *args, **kwargs):
        instance = super(RegisterForm, self).save(commit=commit)
        instance.set_password(self.cleaned_data.get('password'))
        instance.save()
        return instance

    def clean(self):
        cleaned_data = super().clean()
        mobile_number = cleaned_data.get("mobile_number")
        mob = re.match(r'^[6-9]\d{9}$', mobile_number)
        if mob is None:
            raise forms.ValidationError("mobile no must be 10 digits ")


class LoginForm(forms.Form):
    username = forms.CharField(required=True,
                               widget=forms.TextInput(
                                   attrs={'placeholder': 'enter your username'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder': 'enter your password'}))


class ContactForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={"rows": 5, "cols": 20}))

    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
        exclude = ('created_date',)

BookMyDoc/user/views.py
from django.contrib import messages
from django.core.serializers import json
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.views.generic import FormView, View, CreateView
from .forms import RegisterForm, LoginForm, ContactForm
from patient.models import Patient
from django.contrib.auth import authenticate, login, logout
from datetime import datetime
from .models import User, Carousel


# Create your views here.
class IndexView(View):
    template_name = 'user/index.html'

    def get(self, request):
        hospital_user = User.objects.filter(is_type="hospital")
        patient_user = User.objects.filter(is_type="patient")
        doc_user = User.objects.filter(is_type="doctor")
        carousel_images = Carousel.objects.all()
        return render(request, self.template_name, {'hospital_user': hospital_user,
                                                    'patient_user': patient_user,
                                                    'doc_user': doc_user,
                                                    'carousel_images': carousel_images})


class AboutUsView(View):
    template_name = 'user/about_us.html'

    def get(self, request):
        return render(request, self.template_name, {})


class ContactView(View):
    template_name = 'user/contact.html'
    form_class = ContactForm

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        current_date = datetime.now().date()
        form = self.form_class(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.created_date = current_date
            instance.save()
            messages.success(request, 'message send successful.')
            return redirect('user:contact')
        else:
            print(form.errors)
            return render(request, self.template_name, {'form': form})


class RegisterView(View):
    template_name = 'user/register.html'
    form_class = RegisterForm
    success_url = "/user/"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        html_form = render_to_string(self.template_name,
                                     context,
                                     request=request,
                                     )
        return JsonResponse({'html_form': html_form})

    def post(self, request, *args, **kwargs):
        data = dict()
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            patient = Patient(
                user_id=user.id
            )
            patient.save()
            messages.success(self.request, 'your registration will successfull.')
            data['form_is_valid'] = True
            return JsonResponse(data)
            # return redirect(self.success_url)
        else:
            data['form_is_valid'] = False
            context = {'form': form}
            data['html_form'] = render_to_string(self.template_name,
                                                 context,
                                                 request=request,
                                                 )
            return JsonResponse(data)


class LoginView(View):
    form_class = LoginForm
    template_name = 'user/login.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        if request.user.is_authenticated:

            html_form = render_to_string(self.template_name,
                                         context,
                                         request=request,
                                         )
            return JsonResponse({'html_form': html_form})
        else:
            html_form = render_to_string(self.template_name,
                                         context,
                                         request=request,
                                         )
            return JsonResponse({'html_form': html_form})

    def post(self, request, *args, **kwargs):
        data = dict()
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)

                if user.is_type == "patient":
                    messages.success(request, 'Patient login successful')
                    data['form_is_valid'] = "patient"
                    return JsonResponse(data)
                elif user.is_type == "hospital":
                    messages.success(request, 'Hospital login successful')
                    data['form_is_valid'] = "hospital"
                    return JsonResponse(data)
                else:
                    messages.success(request, 'Doctor login successful')
                    data['form_is_valid'] = "doctor"
                    return JsonResponse(data)
            else:
                messages.error(request, 'username password is invalid')
                data['form_is_valid'] = False
                context = {'form': form}
                data['html_form'] = render_to_string(self.template_name,
                                                     context,
                                                     request=request,
                                                     )
                return JsonResponse(data)


def LoginMixin(request):

    return render(request, 'user/demo.html',{})


class PasswordResetCompleteView(View):

    def get(self, request):
        messages.success(request, 'Your password has been set. You may go ahead and sign in')
        return redirect('user:index')


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, 'logout successfull.')
        return redirect('user:index')
    else:
        messages.error(request, 'you are all ready logout.')
        return redirect('user:index')


def index_login(request):
    return render(request, 'index.html', {})

BookMyDoc/templates/user/about_us.html
{% extends 'base.html' %}
{% block title %}About us page {% endblock %}
{% block content %}
<br>

<div class="about">
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <div class="section_title">A few words about us</div>
                <div class="section_subtitle">too choose from</div>
            </div>

        </div>
        <div class="row">


            <div class="col-md-12">
                <br>
                <p style="color: black;">For millions of people, Bookmydoc is the trusted and familiar home where they know
                    they’ll find a healing touch. It connects them with everything they need to take good care of
                    themselves and their family - assessing health issues, finding the right doctor, booking diagnostic
                    tests, obtaining medicines, storing health records or learning new ways to live healthier.</p>

                    <p style="color: black;">Healthcare providers can also harness the power of Bookmydoc as the definitive platform that helps them
                    build their presence, grow establishments and engage patients more deeply than ever.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

BookMyDoc/templates/user/contact.html
{% extends 'base.html' %}
{% block title %}Contact Page{% endblock %}
{% load widget_tweaks %}
{% block content %}
{% include 'partials/messages.html' %}
<div class="contact">
            <center><h2>Contact</h2></center>

    <div class="container">
        <div class="row">
            <div class="col-lg-8 contact_col">
                <div class="contact_form">
                    <div class="contact_title">Get in touch</div>
                    <div class="contact_form_container">
                        <form action="{% url 'user:contact' %}" id="contact_form" class="contact_form" method="post">
                            {% csrf_token %}
                            {% if form.errors %}
                            {% for field in form %}
                            {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endif %}
                          {% for field in form.visible_fields %}
                             <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                             {{ field|add_class:'contact_input' }}
                           {% endfor %}
                            <button class="contact_button" id="contact_button">send message</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 contact_col">
                <div class="contact_info_list">
                    <div class="contact_info_title">Contact Info</div>
                <ul>
                    <li><span>Address: </span>Mitlton Str. 26-27 Gibraltar</li>
                    <li><span>Email: </span>bookmydoc@gmail.com</li>
                    <li><span>Phone: </span>+91 8758162943</li>
                </ul>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

BookMyDoc/templates/user/demo.html
{% include 'user/index.html' %}

<script>
$(document).ready(function() {
    $('#login-form').trigger('click');
});

</script>

BookMyDoc/templates/user/index.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}
{% load static %}
{% block content %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        {% for carousel_image in carousel_images %}
        {% if forloop.first %}
        <div class="carousel-item active">
            {% else %}
            <div class="carousel-item">
                {% endif %}
                <img class="d-block w-100" src="{{carousel_image.image.url}}"
                     alt="First slide" style="height: 70%;">
            </div>
            {% endfor %}
        </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
{% include 'partials/messages.html' %}


<div class="info">
    <div class="container">
        <div class="row row-eq-height">

            <!-- Info Box -->
            <div class="col-lg-4 info_box_col">
                <div class="info_box">
                    <div class="info_image"><img src="{% static 'images/info_1.jpg' %}" alt=""></div>
                    <div class="info_content">
                        <div class="info_title">Emergency Diagnostics</div>
                        <div class="info_text">Our emergency diagnostics services help you get the most accurate
                            diagnosis in a minimal time.
                        </div>
                        <!--							<div class="button info_button"><a href="#"><span>read more</span><span>read more</span></a></div>-->
                    </div>
                </div>
            </div>

            <!-- Info Box -->

            <div class="col-lg-4 info_box_col">
                <div class="info_box">
                    <div class="info_image"><img src="{% static 'images/info_2.jpg' %}" alt=""></div>
                    <div class="info_content">
                        <div class="info_title">Qualified Specialists</div>
                        <div class="info_text">We hire the best specialists to deliver top-notch diagnostic services
                            for you.
                        </div>
                        <!--							<div class="button info_button"><a href="#"><span>read more</span><span>read more</span></a></div>-->
                    </div>
                </div>
            </div>

        </div>


        <br>

        <div class="row">
            <div class="col-sm-6 col-lg-4">
                <div class="card" style="max-width: 18rem;">
                    <div class="card-header bg-behance content-center" style="background-color: #20c997;">
                    </div>
                    <div class="card-body row text-center">
                        <i class="fa fa-users fa-3x" aria-hidden="true" style="color: black;"></i>
                        <div class="col">
                            <div class="info_title" style="color: black;">0{{patient_user.count}}</div>
                            <div class="info_text" style="color: black;">Total registered patient</div>
                        </div>
                        <div class="vr"></div>

                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-4">
                <div class="card" style="max-width: 18rem;">
                    <div class="card-header bg-behance content-center" style="background-color: #20c997;">
                    </div>
                    <div class="card-body row text-center">
                        <i class="fa fa-user-md fa-3x" aria-hidden="true" style="color: black;"></i>
                        <div class="col">


                            <div class="info_title" style="color: black;">0{{doc_user.count}}</div>
                            <div class="info_text" style="color: black;">Total registered doctors</div>
                        </div>
                        <div class="vr"></div>

                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-4">
                <div class="card" style="max-width: 18rem;">
                    <div class="card-header bg-behance content-center" style="background-color: #20c997;">
                    </div>
                    <div class="card-body row text-center">
                        <i class="fa fa-hospital-o fa-3x" style="color: black;"></i>

                        <div class="col">


                            <div class="info_title" style="color: black;">{{hospital_user.count}}</div>
                            <div class="info_text" style="color: black;">Total registered hospitals</div>
                        </div>
                        <div class="vr"></div>

                    </div>
                </div>
            </div>


        </div>
    </div>

</div>


{% endblock %}
{% block js %}

{% endblock %}

BookMyDoc/templates/user/login.html
{% load crispy_forms_tags %}
<form method="post" action="{% url 'user:login' %}" class="login_form">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">login</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% include 'partials/messages.html' %}

        <div class="row">
            <div class="col-md-8">
                {{ form.username|as_crispy_field }}
            </div>
            <div class="col-md-8">
                {{ form.password|as_crispy_field }}
            </div>
        </div>

        <input type="submit" value="submit" class="btn btn-primary">
        <input type="reset" value="clear" class="btn btn-success">
        <p>Forgot <a href="{% url 'user:password_reset' %}" class="blue-text">Password?</a></p>
    </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
</form>

BookMyDoc/templates/user/register.html
{% load crispy_forms_tags %}


<form method="post" action="{% url 'user:register' %}" class="reg_form">

    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Register </h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% if form.errors %}
        <ul style="color: red;">
            {{ form.non_field_errors }}
            <li><font color="red">{{ form.error }}</font></li>
        </ul>
        {% endif %}
        <div class="row">
            <div class="col-md-10">
                {{ form.first_name|as_crispy_field }}
            </div>
            <div class="col-md-10">
                {{ form.last_name|as_crispy_field }}
            </div>
            <div class="col-md-10">
                {{ form.username|as_crispy_field }}
            </div>
            <div class="col-md-10">
                {{ form.email|as_crispy_field }}
            </div>
            <div class="col-md-10">
                {{ form.password|as_crispy_field }}
            </div>
            <div class="col-md-10">
                {{ form.mobile_number|as_crispy_field }}
            </div>
        </div>
        <!--                    {{ form|crispy }}-->
        <input type="submit" value="submit" class="btn btn-primary">
        <input type="reset" value="clear" class="btn btn-success">
    </div>
    <div class="options text-center text-md-left mt-2">
        <p> If You Want To Register Hospital/Clinic? <a href="{% url 'hospital:hospital_request' %}">Click Here</a></p>
    </div>
<!--    <div class="options text-left">-->
<!--        <p class="pt-1">Already have an account? <a href="{% url 'user:login' %}" class="blue-text">Log In</a></p>-->
<!--    </div>-->
    <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
    </div>
</form>