BookMyDoc/BookMyDoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('patient/', include('patient.urls')),
    path('hospital/', include('hospital.urls')),
    path('doctor/', include('doctor.urls')),
    path('', RedirectView.as_view(url='user/')),
    path('', include('django.contrib.auth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BookMyDoc/doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'
urlpatterns = [
    path('index', views.index, name="index"),
    path('dashboard', views.DoctorDashboardView.as_view(), name="dashboard"),
    path('doc_profile/<int:pk>', views.DoctorProfileView.as_view(), name="doc_profile"),
    path('doc_qualification', views.QualificationView.as_view(), name="doc_qualification"),
    path('delete_doc_qualification/<int:pk>', views.DeleteDocQualification.as_view(), name="delete_doc_qualification"),
    path('edit_doc_qualification/<int:pk>', views.EditDocQualification.as_view(), name="edit_doc_qualification"),
    path('doc_time_slot', views.DocTimeSlotView.as_view(), name="doc_time_slot"),
    path('edit_doc_time_slot/<int:pk>', views.EditDocTimeSlot.as_view(), name="edit_doc_time_slot"),
    path('delete_doc_time_slot/<int:pk>', views.DeleteDocTimeSlot.as_view(), name="delete_doc_time_slot"),
    path('today_appointments', views.TodayAppointments.as_view(), name="today_appointments"),
    path('cancel_today_appointments/<int:pk>', views.CancelTodayAppointments.as_view(), name="cancel_today_appointments"),
    path('change_appointment_status', views.ChangeAppointmentStatus.as_view(), name="change_appointment_status"),
    path('check_status', views.CheckStatus.as_view(), name="check_status"),
    path('all_appointments', views.AllAppointments.as_view(), name="all_appointments"),
    path('cancel_appointments/<int:pk>', views.CancelAppointments.as_view(), name="cancel_appointments"),
    path('patient_medical_history/<int:pk>', views.PatientMedicalHistory.as_view(), name="patient_medical_history"),
    path('all_hospital', views.AllHospitalView.as_view(), name="all_hospital"),
    path('doctor_list_view/<int:pk>', views.DoctorListView.as_view(), name="doctor_list_view"),
    path('other_appointments', views.OtherAppointmentView.as_view(), name="other_appointments"),
    path('status_filter', views.StatusFilter.as_view(), name="status_filter"),
    path('show_checkup_timing', views.ShowCheckupTiming.as_view(), name="show_checkup_timing")



]

BookMyDoc/hospital/urls.py
from django.urls import path
from . import views
from .views import HospitalProfile

app_name = "hospital"
urlpatterns = [
    path('index', views.index, name="index"),
    path('hospital_dashboard', views.HospitalDashboard.as_view(), name="hospital_dashboard"),
    path('hospital_request', views.HospitalClinicRequest.as_view(), name="hospital_request"),
    path('hospital_profile/<int:pk>', HospitalProfile.as_view(), name="hospital_profile"),
    path('add_doctor', views.AddDoctor.as_view(), name="add_doctor"),
    path('doc_list', views.AllDoctorListView.as_view(), name="doc_list"),
    path('appointment_slot/<int:pk>', views.AppointmentTimeSlotView.as_view(), name="appointment_slot"),
    path('appointment_book', views.AppointmentBookView.as_view(), name="appointment_book"),
    path('upload_hospital_images', views.UploadHospitalImages.as_view(), name="upload_hospital_images"),
    path('all_hospital_images', views.AllHospitalImages.as_view(), name="all_hospital_images"),
    path('hospital_delete_image/<int:pk>', views.HospitalDeleteImage.as_view(), name="hospital_delete_image"),
    path('all_doctor_list', views.AllDocList.as_view(), name="all_doctor_list"),
    path('delete_doc/<int:pk>', views.DeleteDoc.as_view() , name="delete_doc")

]

BookMyDoc/patient/urls.py
from django.urls import path
from . import views
from .views import UserProfile, PatientMedicalHistory
app_name = 'patient'
urlpatterns = [
    path('index', views.index, name="index"),
    path('wrong', views.write, name="wrong"),
    path('user_profile/<int:pk>', UserProfile.as_view(), name="user_profile"),
    path('patient_medical_history', PatientMedicalHistory.as_view(), name="patient_medical_history"),
    path('all_hospital', views.DisplayHospital.as_view(), name="all_hospital"),
    path('hospital_detail/<int:pk>/', views.HospitalDetailView.as_view(), name="hospital_detail"),
    path('booking/<int:pk>', views.BookingView.as_view(), name="booking"),
    path('time_slot', views.AppointmentBooking.as_view(), name="time_slot"),
    path('my_appointments', views.MyAppointmentsView.as_view(), name="my_appointments"),
    path('cancel_appointments/<int:pk>', views.CancelAppointments.as_view(), name="cancel_appointments"),
]

BookMyDoc/user/urls.py
from django.urls import path, include
from . import views
from .views import RegisterView, LoginView
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('about_us', views.AboutUsView.as_view(), name="about_us"),
    path('contact', views.ContactView.as_view(), name="contact"),
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('login_mixin', views.LoginMixin, name="login_mixin"),
    path('logout/', views.logout_view, name="logout"),
    path('index_login', views.index_login, name="index_login"),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('%5reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

BookMyDoc/doctor/models.py
# import self as self
from django.db import models
from django.contrib.auth import get_user_model
from hospital.models import Hospital
from patient.models import Patient
import datetime

User = get_user_model()


# Create your models here.

class DoctorProfile(models.Model):
    SPECIALIZATION = (
        ('dentist', 'Dentist'),
        ('general physician', 'General Physician'),
        ('pediatrician', 'Pediatrician'),
        ('ayurveda', 'Ayurveda'),
        ('orthopedist', 'Orthopedist'),
        ('dental surgeon', 'Dental Surgeon'),
        ('dermatologist', 'Dermatologist'),
        ('general surgeon', 'General Surgeon'),
        ('gynecologist', 'Gynecologist'),

    )

    COUNCIL = (
        ('tamil nadu medical council', 'Tamil Nadu Medical Council'),
        ('medical council of india', 'Medical Council of India'),
        ('andhra pradesh medical council', 'Andhra Pradesh Medical Council'),
        ('assam medical council', 'Assam Medical Council'),
        ('bhopal medical council', 'Bhopal Medical Council'),
        ('bihar medical council', 'Bihar Medical Council'),
        ('bombay medical council', 'Bombay Medical Council'),
        ('chandigarh medical council', 'Chandigarh Medical Council'),
        ('chattisgarh medical council', 'Chattisgarh Medical Council'),
        ('delhi medical council', 'Delhi Medical Council'),
        ('gujarat medical council', 'Gujarat Medical Council'),
        ('goa medical council', 'Goa Medical Council'),
        ('haryana medical council', 'Haryana Medical Council'),
        ('hyderabad medical council', 'Hyderabad Medical Council')
    )
    specialization = models.CharField(max_length=20, choices=SPECIALIZATION)
    registration_no = models.CharField(max_length=20)
    council = models.CharField(max_length=50, choices=COUNCIL)
    experience = models.IntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                blank=True, related_name='doctor_profile')
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE,
                                 blank=True, related_name='doctor_pro')

    def __str__(self):
        return self.user.username


class DoctorDegree(models.Model):
    degree = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return self.degree


class DoctorUniversity(models.Model):
    university_name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return self.university_name


class Qualification(models.Model):
    # doc_degree = DoctorDegree.objects.all()
    # doc_university = DoctorUniversity.objects.all()
    doctor_profile = models.ForeignKey(DoctorProfile, on_delete=models.CASCADE,
                                       related_name='qualification', blank=True)
    degree = models.CharField(max_length=20)
    university = models.CharField(max_length=80)
    year_completion = models.IntegerField(null=True)

    def __str__(self):
        return self.doctor_profile.user.first_name


class DocTimeSlot(models.Model):
    DAY = (
        ('monday', 'Monday'),
        ('tuesday', 'Tuesday'),
        ('wednesday', 'Wednesday'),
        ('thursday', 'Thursday'),
        ('friday', 'Friday'),
        ('saturday', 'Saturday'),
        ('sunday', 'Sunday')
    )

    doc = models.ForeignKey(DoctorProfile, on_delete=models.CASCADE,
                            related_name='doc_time_slot', blank=True)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE,
                                 related_name='hospital_time_slot', blank=True)
    days = models.CharField(max_length=10, choices=DAY)
    from_time = models.TimeField()
    to_time = models.TimeField()

    def __str__(self):
        return self.doc.user.username


class Appointment(models.Model):
    Booked = 'Booked'
    Ongoing = 'Ongoing'
    Completed = 'Completed'
    Cancel = 'Cancel'

    APPOINTMENT_STATUS = (
        (Booked, "Booked"),
        (Ongoing, "Ongoing"),
        (Completed, "Completed"),
        (Cancel, "Cancel"),
    )
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, related_name='hospital_id', null=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_id', null=True)
    doctor = models.ForeignKey(DoctorProfile, on_delete=models.CASCADE, related_name='doc_id', blank=True)
    date = models.DateField()
    time_slot = models.ForeignKey(DocTimeSlot, on_delete=models.CASCADE, related_name='time_slot', blank=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='app_create', blank=True)
    canceled_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='app_cancel', null=True)
    status = models.CharField(max_length=10, choices=APPOINTMENT_STATUS, null=True, blank=True)


class CheckupTiming(models.Model):
    appointment = models.OneToOneField(Appointment, on_delete=models.CASCADE, related_name='appointment_id',
                                       null=True, blank=True)
    doc = models.ForeignKey(DoctorProfile, on_delete=models.CASCADE, related_name='doc_pro_id',
                            null=True, blank=True)
    date = models.DateField()
    check_in = models.TimeField(blank=True, null=True)
    check_out = models.TimeField(blank=True, null=True)

BookMyDoc/doctor/forms.py
from django import forms
from django.forms import TimeField
from .models import DoctorProfile, Qualification, DocTimeSlot,DoctorDegree, DoctorUniversity
from django.contrib.auth import get_user_model
import datetime

User = get_user_model()


class DoctorProfileForm(forms.ModelForm):
    experience = forms.CharField(required=True)

    class Meta:
        model = DoctorProfile
        fields = '__all__'
        exclude = ('user', 'hospital')


class DoctorUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email', 'mobile_number', 'gender',
                  'profile_image']
        help_texts = {
            'username': None

        }


def year_choices():
    return [(r, r) for r in range(1987, datetime.date.today().year + 1)]


def current_year():
    return datetime.date.today().year


class QualificationForm(forms.ModelForm):
    degree = forms.ModelChoiceField(queryset=DoctorDegree.objects.all())
    university = forms.ModelChoiceField(queryset=DoctorUniversity.objects.all())
    year_completion = forms.TypedChoiceField(choices=year_choices, initial=current_year)

    class Meta:
        model = Qualification
        fields = '__all__'
        exclude = ('doctor_profile',)


class DocTimeSlotForm(forms.ModelForm):
    # morning_from = forms.TimeField(input_formats=['%I:%M %p'],
    #                                widget=forms.TimeInput(format='%I:%M %p'))
    # morning_to = forms.TimeField(input_formats=['%I:%M %p'],
    #                              widget=forms.TimeInput(format='%I:%M %p'))
    # evening_from = forms.TimeField(input_formats=['%I:%M %p'],
    #                                widget=forms.TimeInput(format='%I:%M %p'))
    # evening_to = forms.TimeField(input_formats=['%I:%M %p'],
    #                              widget=forms.TimeInput(format='%I:%M %p'))

    class Meta:
        model = DocTimeSlot
        fields = '__all__'
        from_time = forms.TimeField(
            widget=forms.TimeInput(attrs={'class': 'time'}))
        to_time = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'time'}))

        # widgets = {'from_time': TimeField(attrs={'class': 'ui-timepicker-input'})}
        exclude = ('doc', 'hospital',)

BookMyDoc/templates/doctor/all_appointments.html
{% extends 'base.html' %}
{% block title %}Doctor All Appointments Page{% endblock %}
{% block content %}
{% include 'partials/messages.html' %}
<div class="container">
    <div class="page-header">
        <center><h2>
            All Appointment List
        </h2></center>
    </div>
<form method="get" action="{% url 'doctor:status_filter' %}">
    <select type="select" style="width: 30%;" name="status_filter" class="form-control" onchange="this.form.submit()">
        <option>--Search By Status--</option>
        <option value="Booked">Booked</option>
        <option value="Completed">Completed</option>
        <option value="Cancel">Cancel</option>
    </select>
    </form>
    <br>
    <table border="1" class="responstable" id="all_appointment">
        <thead>
        <tr>
            <th>Patient Name</th>
            <th>Hospital Name</th>
            <th>Doctor Name</th>
            <th>Appointment Date</th>
            <th>Appointment Slot</th>
            <th>Created By</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for appointment in appointment_list %}

        <tr>

            <td>
                <a href="{% url 'doctor:patient_medical_history' appointment.id %}">
                    {% if appointment.patient.user.first_name is None %}
                    {{appointment.patient.first_name}}
                    {% else %}
                    {{appointment.patient.user.first_name}}
                    {% endif %}
                </a>

            </td>
            <td>{{appointment.hospital.name}}</td>
            <td>{{appointment.doctor.user.first_name}} {{appointment.doctor.user.last_name}}</td>
            <td>{{appointment.date|date:"D, d M, Y" }}</td>
            <td>{{appointment.time_slot.from_time|time:"h:i a"}} to {{appointment.time_slot.to_time|time:"h:i a"}}</td>
            <td>{{appointment.created_by.is_type}}</td>
            <td>{{appointment.status}}</td>
            <td>
            {% if appointment.status == 'Booked' %}
                <form method="post" action="{% url 'doctor:cancel_appointments' appointment.id %}"
                      id="cancel-booking" class="cancel-booking">
                    {% csrf_token %}
                    <button class="btn btn-danger fa fa-trash"></button>
                </form>

            {% elif appointment.status == 'Cancel' %}

            {% elif appointment.status == 'Ongoing' %}

             {% else %}

                 <button id="{{appointment.id}}" class="btn btn-danger fa fa-question-circle dtaa" ></button>

            {% endif %}
            </td>
        </tr>

        {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="show_checkup_time" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
             <h4 class="modal-title">Checkup time</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>

        </div>
        <div class="modal-body" style="color: black;">
                  </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

{% endblock %}
{% block js %}
<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
        }
    }
});

$(document).ready(function() {
    $('#all_appointment').DataTable({
        "ordering": true,
        "info":     false,
        "order": [[ 6, 'asc' ]]
    });

    $('.cancel-booking').on('submit', function(event){

              var r = confirm("Are You Sure!");
              if (r == true) {

              }
              else
              {
                 event.preventDefault();
               }
});
$('.dtaa').click(function(e){
     var app_id = $(this).attr('id');

    e.preventDefault(); // avoid to execute the actual submit of the form.

    var url = "{% url 'doctor:show_checkup_timing' %}";
    $.ajax({
           type: 'get',
           url: url,
           data : { appointment_id : app_id
                      },
           success: function(data)
           {
              console.log(data);
              $("#show_checkup_time").modal("show");
              $("#show_checkup_time .modal-body").html('Patient checkup time is <b>'+ data.duration_hour + '</b> : <b>'+ data.duration_minute +'</b> : <b>'+data.duration_sec+'</b>');
           },
           error: function(data) {
                console.log(data);
            }

         });

});



});

</script>
{% endblock %}

BookMyDoc/templates/doctor/doc_profile.html
{% extends 'base.html' %}
{% block title %}Doctor Profile Page{% endblock title %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="page-header">
        <center><h2>
            Doctor Profile
        </h2></center>
    </div>
    <div class="row">
        <div class="col-md-8">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {{ user_form|crispy }}
                {{ form|crispy }}

                <input type="submit" value="submit" class="btn btn-primary">
                <input type="reset" value="clear" class="btn btn-success">

            </form>
        </div>
    </div>
</div>

{% endblock %}

BookMyDoc/templates/doctor/doc_time_slot.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Doctor Time Slot Page{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'partials/messages.html' %}
<div class="container">
    <div class="page-header">
        <center><h2>
            Doctor TimeSlot
        </h2></center>
    </div>
    <div class="row">
        <div class="col-md-8" style="color: black;">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="submit" class="btn btn-primary">
                <input type="reset" value="reset" class="btn btn-success">
            </form>
        </div>
    </div>

<br><br>
    <div class="row">
        <div class="col-md-12" id="data_show">
            <input type="hidden" id="time_slot_data" value="{{doc_time_slot}}">

            <table id="doc_timeslot" class="responstable">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Doctor Name</th>
                    <th>Day</th>
                    <th>From Time</th>
                    <th>To Time</th>
                    <th>Action</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for i in doc_time_slot %}

                <tr>
                    <!--|time:"H:i p" -->
                    <td>{{forloop.counter}}</td>
                    <td>{{i.doc}}</td>
                    <td>{{ i.days}}</td>
                    <td>{{i.from_time|time:"h:i a"}}</td>
                    <td>{{i.to_time|time:"h:i a"}}</td>

                    <td><a href="{% url 'doctor:edit_doc_time_slot' i.id %}" class="btn"
                           style="background-color: #019658; color: white;">
                        <i class="fa fa-pencil" aria-hidden="true"></i> edit</a>
                    </td>
                    <td><a href="{% url 'doctor:delete_doc_time_slot' i.id %}"
                            class="btn btn-danger" style="color: white;">
                        <i class="fa fa-trash" aria-hidden="true"></i> delete</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

{% block js %}
<script>
$(document).ready(function() {
    var data = $('#time_slot_data').val();

    if(data == "")
    {
        $('#data_show').hide();

    }
    $('#doc_timeslot').DataTable({
        "ordering": false,
        "info":     false
    });
 });
</script>
<script type="text/javascript">

 $(function() {
	$('#id_from_time').timepicker({
	'timeFormat': 'H:i'

	});
	$('#id_from_time').on('changeTime', function() {
	 var first_time = $(this).val();
        var arr = first_time.split(':');
        var hrs = arr[0];
        var new_hrs = parseInt(hrs)+01;

        if(new_hrs>24)
         new_hrs = new_hrs-24;

         if(new_hrs < 10)
          new_hrs  = '0'+new_hrs;

        var second_time = new_hrs+':'+arr[1];
        $('#id_to_time').val(second_time);
});
});
$(function() {
    $('#id_to_time').timepicker({
        timeFormat: 'H:i',

   });
	$('#id_to_time').on('changeTime', function() {

        var to = $('#id_to_time').val();
        var from = $('#id_from_time').val();


        if (from == "")
        {
            alert("Please enter from time first.");
            $('#id_to_time').val("");

        }
        if(to <= from)
        {
            alert("you can not enter less time than from");
            $('#id_to_time').val("");
        }
    });
});


</script>

{% endblock %}

BookMyDoc/templates/doctor/doctor_dashboard.html
{% extends 'base.html' %}
{% block title %}Doctor Dashboard Page{% endblock %}
{% block content %}
{% include 'partials/messages.html' %}
<div class="container">
    <div class="page-header">
        <center><h2>
            Dashboard
        </h2></center>
    </div>
    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'doctor:today_appointments' %}">
                <div class="card text-white mb-3" style="max-width: 16rem; background: #28a745eb;">
                    <!--  <div class="card-header">Appointments</div>-->
                    <div class="card-body">
                        <h4 class="card-title">Today Appointments</h4>
                        <div class="rotate">
                            <i class="fa fa-address-book-o fa-3x"></i>
                            <div align="right"><span class="badge badge-danger ml-3"
                                                     style="font-size: 17px;">{{today_appointments.count}}</span>
                            </div>

                        </div>

                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'doctor:all_appointments' %}">
                <div class="card text-white mb-3" style="max-width: 16rem; background: #17a2b8;">
                    <!--  <div class="card-header">Appointments</div>-->
                    <div class="card-body">
                        <h4 class="card-title">All Appointments</h4>
                        <div class="rotate">
                            <i class="fa fa-list-alt fa-3x"></i>
                            <div align="right">
                                <span class="badge badge-danger ml-3" style="font-size: 17px;">{{appointment_list.count}}</span>
                            </div>
                        </div>

                        <p class="card-text-right"></p>
                    </div>
                </div>
            </a>
        </div>
<!--        <div class="col-md-4">-->
<!--            <a href="{% url 'doctor:other_appointments' %}">-->
<!--                <div class="card text-white mb-3" style="max-width: 16rem; background: #ff8d00d6;">-->
<!--                    &lt;!&ndash;  <div class="card-header">Appointments</div>&ndash;&gt;-->
<!--                    <div class="card-body">-->
<!--                        <h4 class="card-title">Other Appointments</h4>-->
<!--                        <div class="rotate">-->
<!--                            <i class="fa fa-th-list fa-3x"></i>-->
<!--                            <div align="right">-->
<!--                                <span class="badge badge-danger ml-3" style="font-size: 17px;">{{other_appointment_list.count}}</span>-->
<!--                            </div>-->
<!--                        </div>-->

<!--                        <p class="card-text-right"></p>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </a>-->
<!--        </div>-->
        <div class="col-md-4">
            <a href="{% url 'doctor:doc_profile' request.user.id %}">
                <div class="card text-white mb-3" style="max-width: 16rem; background: #f99;">
                    <!--  <div class="card-header">Appointments</div>-->
                    <div class="card-body">
                        <h4 class="card-title">User Profile</h4>
                        <div class="rotate">
                            <i class="fa fa-user fa-3x"></i>
                        </div>

                        <p class="card-text-right"></p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'doctor:doc_qualification' %}">
                <div class="card text-white mb-3" style="max-width: 16rem; background: #ff5e00;">
                    <!--  <div class="card-header">Appointments</div>-->
                    <div class="card-body">
                        <h4 class="card-title">Qualification</h4>
                        <div class="rotate">
                            <i class="fa fa-graduation-cap fa-3x"></i>
                        </div>

                        <p class="card-text-right"></p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'doctor:doc_time_slot' %}">
                <div class="card text-white mb-3" style="max-width: 16rem; background: #ff2489e0;">
                    <!--  <div class="card-header">Appointments</div>-->
                    <div class="card-body">
                        <h4 class="card-title">Add Timeslot</h4>
                        <div class="rotate">
                            <i class="fa fa-clock-o fa-3x"></i>
                        </div>

                        <p class="card-text-right"></p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'doctor:all_hospital' %}">
                <div class="card text-white mb-3" style="max-width: 16rem; background: #007bff;">
                    <!--  <div class="card-header">Appointments</div>-->
                    <div class="card-body">
                        <h4 class="card-title">All Hospital</h4>
                        <div class="rotate">
                            <i class="fa fa-hospital-o fa-3x"></i>
                        </div>

                        <p class="card-text-right"></p>
                    </div>
                </div>
            </a>
        </div>


    </div>


</div>

{% endblock %}

BookMyDoc/templates/doctor/edit_doc_qualification.html
{% extends 'base.html' %}
{% block title %}Doctor Qualification Page{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
{% include 'partials/messages.html' %}
<div class="container">
    <div class="page-header">
        <center><h2>
           Edit Doctor Qualification
        </h2></center>
    </div>
    <div class="row">
        <div class="col-md-8">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary" value="submit">
                <input type="reset" class="btn btn-success" value="clear">
            </form>
        </div>
    </div>
</div>
{% endblock %}