BookMyDoc/BookMyDoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('patient/', include('patient.urls')),
    path('hospital/', include('hospital.urls')),
    path('doctor/', include('doctor.urls')),
    path('', RedirectView.as_view(url='user/')),
    path('', include('django.contrib.auth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BookMyDoc/doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'
urlpatterns = [
    path('index', views.index, name="index"),
    path('dashboard', views.DoctorDashboardView.as_view(), name="dashboard"),
    path('doc_profile/<int:pk>', views.DoctorProfileView.as_view(), name="doc_profile"),
    path('doc_qualification', views.QualificationView.as_view(), name="doc_qualification"),
    path('delete_doc_qualification/<int:pk>', views.DeleteDocQualification.as_view(), name="delete_doc_qualification"),
    path('edit_doc_qualification/<int:pk>', views.EditDocQualification.as_view(), name="edit_doc_qualification"),
    path('doc_time_slot', views.DocTimeSlotView.as_view(), name="doc_time_slot"),
    path('edit_doc_time_slot/<int:pk>', views.EditDocTimeSlot.as_view(), name="edit_doc_time_slot"),
    path('delete_doc_time_slot/<int:pk>', views.DeleteDocTimeSlot.as_view(), name="delete_doc_time_slot"),
    path('today_appointments', views.TodayAppointments.as_view(), name="today_appointments"),
    path('cancel_today_appointments/<int:pk>', views.CancelTodayAppointments.as_view(), name="cancel_today_appointments"),
    path('change_appointment_status', views.ChangeAppointmentStatus.as_view(), name="change_appointment_status"),
    path('check_status', views.CheckStatus.as_view(), name="check_status"),
    path('all_appointments', views.AllAppointments.as_view(), name="all_appointments"),
    path('cancel_appointments/<int:pk>', views.CancelAppointments.as_view(), name="cancel_appointments"),
    path('patient_medical_history/<int:pk>', views.PatientMedicalHistory.as_view(), name="patient_medical_history"),
    path('all_hospital', views.AllHospitalView.as_view(), name="all_hospital"),
    path('doctor_list_view/<int:pk>', views.DoctorListView.as_view(), name="doctor_list_view"),
    path('other_appointments', views.OtherAppointmentView.as_view(), name="other_appointments"),
    path('status_filter', views.StatusFilter.as_view(), name="status_filter"),
    path('show_checkup_timing', views.ShowCheckupTiming.as_view(), name="show_checkup_timing")



]

BookMyDoc/hospital/urls.py
from django.urls import path
from . import views
from .views import HospitalProfile

app_name = "hospital"
urlpatterns = [
    path('index', views.index, name="index"),
    path('hospital_dashboard', views.HospitalDashboard.as_view(), name="hospital_dashboard"),
    path('hospital_request', views.HospitalClinicRequest.as_view(), name="hospital_request"),
    path('hospital_profile/<int:pk>', HospitalProfile.as_view(), name="hospital_profile"),
    path('add_doctor', views.AddDoctor.as_view(), name="add_doctor"),
    path('doc_list', views.AllDoctorListView.as_view(), name="doc_list"),
    path('appointment_slot/<int:pk>', views.AppointmentTimeSlotView.as_view(), name="appointment_slot"),
    path('appointment_book', views.AppointmentBookView.as_view(), name="appointment_book"),
    path('upload_hospital_images', views.UploadHospitalImages.as_view(), name="upload_hospital_images"),
    path('all_hospital_images', views.AllHospitalImages.as_view(), name="all_hospital_images"),
    path('hospital_delete_image/<int:pk>', views.HospitalDeleteImage.as_view(), name="hospital_delete_image"),
    path('all_doctor_list', views.AllDocList.as_view(), name="all_doctor_list"),
    path('delete_doc/<int:pk>', views.DeleteDoc.as_view() , name="delete_doc")

]

BookMyDoc/user/urls.py
from django.urls import path, include
from . import views
from .views import RegisterView, LoginView
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('about_us', views.AboutUsView.as_view(), name="about_us"),
    path('contact', views.ContactView.as_view(), name="contact"),
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('login_mixin', views.LoginMixin, name="login_mixin"),
    path('logout/', views.logout_view, name="logout"),
    path('index_login', views.index_login, name="index_login"),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('%5reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

BookMyDoc/hospital/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.

class Hospital(models.Model):
    CHOICES = (
        ('hospital', 'Hospital'),
        ('clinic', 'Clinic')
    )
    name = models.CharField(max_length=50)
    is_type = models.CharField(max_length=8, choices=CHOICES)
    website = models.URLField()
    address = models.CharField(max_length=500, blank=True)
    no_of_opd = models.IntegerField(default=0)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE,
                                blank=True, related_name='hospital')

    def __str__(self):
        return self.name + "  " + self.is_type


class HospitalRequest(models.Model):
    CHOICES = (
        ('hospital', 'Hospital'),
        ('clinic', 'Clinic')
    )

    name = models.CharField(max_length=50)
    email = models.EmailField()
    mobile = models.CharField(max_length=10)
    type = models.CharField(max_length=8, choices=CHOICES)
    username = models.CharField(max_length=20)
    website = models.URLField()

    def __str__(self):
        return self.name + " " + self.type


class Images(models.Model):
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, related_name='hospital', blank=True, null=True)
    image = models.ImageField(upload_to='images')

BookMyDoc/hospital/views.py
import datetime
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string
from django.views.generic import View, UpdateView, FormView, ListView
from BookMyDoc.settings import EMAIL_HOST_USER
from .forms import HospitalProfileForm, HospitalUserForm, AddDoctorForm, \
    HospitalRequestForm, PatientForm, UploadImages
from .models import Hospital, get_user_model, HospitalRequest, Images
from doctor.models import DoctorProfile, Appointment, DocTimeSlot
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime, timezone


# Create your views here.

def index(request):
    return HttpResponse("hospital index")


class HospitalDashboard(LoginRequiredMixin, View):
    template_name = 'hospital/hospital_dashboard.html'

    def get(self, request):
        return render(request, self.template_name, {})


class HospitalProfile(LoginRequiredMixin, UpdateView):
    form_class = HospitalProfileForm
    second_form_class = HospitalUserForm
    template_name = 'hospital/hospital_profile.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        hospital_profile = Hospital.objects.get(user=user.id)
        user_profile = get_user_model().objects.get(id=user.id)
        form = self.form_class(instance=hospital_profile)
        user_form = self.second_form_class(instance=user_profile)
        return render(request, self.template_name, {'form': form, 'user_form': user_form})

    def post(self, request, *args, **kwargs):
        user = request.user

        hospital_profile = Hospital.objects.get(user=user.id)
        user_profile = get_user_model().objects.get(id=user.id)
        form = self.form_class(request.POST, instance=hospital_profile)
        user_form = self.second_form_class(request.POST, request.FILES, instance=user_profile)
        if form.is_valid() and user_form.is_valid():
            form.save()
            user_form.save()
            return HttpResponse("success")
        else:
            return render(request, self.template_name, {'form': form, 'user_form': user_form})


class AddDoctor(LoginRequiredMixin, FormView):
    template_name = 'hospital/add_doctor.html'
    form_class = AddDoctorForm

    def get(self, request, *args, **kwargs):
        form = self.form_class

        users = request.user.hospital

        if users.is_type == "clinic":

            try:
                clinic_doc = DoctorProfile.objects.get(hospital_id=users.id)
            except ObjectDoesNotExist:
                clinic_doc = None

            if clinic_doc is None:
                return render(request, self.template_name, {'form': form})
            else:
                messages.error(request, 'You can not add multiple doctor.')
                return redirect('hospital:hospital_dashboard')

        else:
            return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            hospital_id = request.user.hospital

            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            mobile_number = form.cleaned_data['mobile_number']
            gender = form.cleaned_data['gender']

            random_pass = get_user_model().objects.make_random_password()
            User = get_user_model()

            user = User(
                first_name=first_name,
                last_name=last_name,
                username=username,
                email=email,
                mobile_number=mobile_number,
                gender=gender,
                is_type="doctor"
            )
            user.set_password(random_pass)
            user.save()

            doc_profile = DoctorProfile(
                hospital_id=hospital_id.id,
                user_id=user.id
            )
            doc_profile.save()
            html_content = 'Your password is:- <p><strong>' + random_pass + '</strong></p>'
            subject = 'Bookmydoc Doctor account password'
            to_mail = email
            msg = EmailMessage(subject, html_content, EMAIL_HOST_USER, [to_mail])
            msg.content_subtype = "html"
            msg.send()
            print(random_pass)
            messages.success(request, 'doctor add successful.')
            return redirect('hospital:add_doctor')
        else:
            return render(request, self.template_name, {'form': form})


class HospitalClinicRequest(FormView):
    template_name = 'hospital/hospital_request.html'
    form_class = HospitalRequestForm

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Hospital/clinic request send successful')
        return redirect('user:index')


class AllDoctorListView(ListView):
    template_name = 'hospital/all_doctor_list.html'

    def get(self, request, *args, **kwargs):
        hospital_id = request.user.hospital.id
        doctor_lists = DoctorProfile.objects.filter(hospital_id=hospital_id)
        return render(self.request, self.template_name, {'doctor_lists': doctor_lists})


class AppointmentTimeSlotView(LoginRequiredMixin, View):
    template_name = 'doctor/appointment_time_slot.html'
    form_class = PatientForm

    def get(self, request, *args, **kwargs):
        doc_id = kwargs.get('pk')
        data = DoctorProfile.objects.get(id=doc_id)
        return render(request, self.template_name, {'data': data})

    def post(self, request, *args, **kwargs):
        doc_id = kwargs.get('pk')

        date = request.POST.get('select_date')
        convert_date = datetime.strptime(date, "%m/%d/%Y").date()
        day_of_week = convert_date.strftime("%A")

        current_date = datetime.now().date()
        current_time = datetime.now().time().strftime('%H:%M')
        convert_time = datetime.strptime(current_time, "%H:%M").time()

        if convert_date == current_date:
            match_booking = Appointment.objects.filter(date=convert_date, doctor_id=doc_id,
                                                       status__in=[Appointment.Booked, Appointment.Ongoing,
                                                                   Appointment.Completed])

            exclude_data = []
            for i in match_booking:
                exclude_data.append(i.time_slot_id)

            doc_time_slot = DocTimeSlot.objects.filter(doc_id=doc_id, days=day_of_week,
                                                       from_time__gte=convert_time).exclude(id__in=exclude_data)

            if not doc_time_slot:
                messages.error(request, "This date in any time slot is not available.")
                html = render_to_string(request=request, template_name='doctor/available_time_slot.html',
                                        context={'doc_time_slot': doc_time_slot})

                return JsonResponse(data={'html': html})

            else:
                form = self.form_class

                html = render_to_string(request=request, template_name='doctor/available_time_slot.html',
                                        context={'doc_time_slot': doc_time_slot,
                                                 'form': form})

                return JsonResponse(data={'html': html})

        else:
            match_booking = Appointment.objects.filter(date=convert_date, doctor_id=doc_id,
                                                       status__in=[Appointment.Booked, Appointment.Ongoing,
                                                                   Appointment.Completed])

            exclude_data = []
            for i in match_booking:
                exclude_data.append(i.time_slot_id)

            doc_time_slot = DocTimeSlot.objects.filter(doc_id=doc_id, days=day_of_week).exclude(id__in=exclude_data)

            if not doc_time_slot:
                messages.error(request, "This date in any time slot is not available.")
                html = render_to_string(request=request, template_name='doctor/available_time_slot.html',
                                        context={'doc_time_slot': doc_time_slot})
                return JsonResponse(data={'html': html})
            else:
                form = self.form_class
                html = render_to_string(request=request, template_name='doctor/available_time_slot.html',
                                        context={'doc_time_slot': doc_time_slot,
                                                 'form': form})
                return JsonResponse(data={'html': html})


class AppointmentBookView(LoginRequiredMixin, View):
    form_class = PatientForm

    def post(self, request):
        date = request.POST.get('selected_date')
        convert_date = datetime.strptime(date, "%m/%d/%Y").date()
        selected_slot_id = request.POST.get('selected_slot')
        selected_time_slot = DocTimeSlot.objects.get(id=selected_slot_id)

        form = self.form_class(request.POST)

        if form.is_valid():
            patient = form.save()

            appointment = Appointment(
                hospital_id=selected_time_slot.hospital_id,
                patient_id=patient.id,
                doctor_id=selected_time_slot.doc_id,
                date=convert_date,
                time_slot_id=selected_time_slot.id,
                created_by=request.user,
                status=Appointment.Booked
            )
            appointment.save()
            messages.success(request, 'appointment is successful booked.')
            return redirect('hospital:doc_list')
        else:
            messages.error(request, 'your form data is not valid.')
            return redirect('hospital:doc_list')

BookMyDoc/templates/hospital/add_doctor.html
{% extends 'base.html' %}
{% block title %}Add Doctor Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'partials/messages.html' %}
<div class="container">
    <div class="page-header">
        <center><h2>
            Add Doctors
        </h2></center>
    </div>
    <div class="row" style="color: black;">
        <div class="col-md-8">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="submit" class="btn btn-primary">
                <input type="reset" value="clear" class="btn btn-success">
            </form>
        </div>
    </div>
</div>

{% endblock %}

BookMyDoc/templates/hospital/all_doctor_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Hospital DoctorList Page{% endblock %}
{% block content %}
<style>
body{
  background: #f2f2f2;
  font-family: 'Open Sans', sans-serif;
}

.search {
  width: 50%;
  position: relative;
  display: flex;
}

.searchTerm {
  width: 50%;
  border: 2px solid #black;
  border-right: none;
  padding: 5px;
  height: 40px;
  border-radius: 5px 0 0 5px;
  outline: none;
  color: black;
}

.searchTerm:focus{
  color: black;
}
</style>
<div class="container">
    {% include 'partials/messages.html' %}

    <div class="page-header">
        <center><h2>
            All Doctors
        </h2></center>
    </div>
<br>
    <input type="text" class="searchTerm" id="SearchTextField" placeholder="Search doctors, specialization, etc.">
    <table id="all_doctors">
        <thead>
        <tr>
            <th style="border-bottom: 0px;">
            </th>
        </tr>
        </thead>
<br>
        <tbody style="color: black;">
        {% for doc_lists in doctor_lists %}
        <tr>
            <td>

                <div class="card mb-3" style="max-width: 680px; border-color: black;">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            {% if doc_lists.user.profile_image %}
                            <img src="{{ doc_lists.user.profile_image.url }}" class="card-img" alt="no image found">
                            {% else %}
                            <img src="{% static 'images/defaultimage.png' %}" class="card-img" alt="no display found">
                            {% endif %}
                        </div>
                        <!--    {{ doc_lists.user.gender}}-->
                        <div class="col-md-8">
                            <div class="card-body">
                                <h4 class="card-title"><font color="black">Dr. {{ doc_lists.user.first_name }}
                                  {{doc_lists.user.last_name }}</font></h4>
                                <h5 class="card-text">{% for qualification in doc_lists.qualification.all %}
                                    {{ qualification.degree|title }}
                                    {% endfor %}
                                </h5>
                                <h5 class="card-text">{{ doc_lists.council }}</h5>
                                <h5 class="card-text">{{ doc_lists.specialization }}</h5>
                                <h5 class="card-text">{{ doc_lists.experience }} years experience overall</h5>
                                <!--        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>-->
                            </div>
                            <div class="text-right">
                                <div class="card-footer">
                                    <a href="{% url 'hospital:appointment_slot' doc_lists.id %}" class="btn btn-sm"
                                       style="background-color: #20c997; color: black; border-color: black;">Book Appointment</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block js %}
<script>
  $(document).ready(function() {
  var all_doc = $('#all_doctors').DataTable({
        "ordering": false,
        "info":     false,
        "lengthChange": false,
        "dom": "tipr"
   });

   $('#SearchTextField').keyup(function(){
      all_doc.search($(this).val()).draw() ;
    });

 });

</script>
{% endblock %}

BookMyDoc/templates/hospital/all_hospital_images.html
{% extends 'base.html' %}
{% block title %}All hospital images page{% endblock %}
{% block content %}
{% include 'partials/messages.html' %}
<div class="container">
    <div class="page-header">
        <center><h2>
            Hospital images
        </h2></center>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <table class="responstable">
                <tr>
                    <th>Hospital name</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
                {% for hospital_image in hospital_images %}
                <tr>
                    <td>{{hospital_image.hospital.name}}</td>
                    <td><img src="{{hospital_image.image.url}}" class="img-thumbnail"></td>
                    <td><a href="{% url 'hospital:hospital_delete_image' hospital_image.id %}" class="btn btn-danger">Delete</a></td>
                </tr>

                {% endfor %}

            </table>
        </div>
    </div>
</div>

{% endblock %}
{% block js %}
<script>
$(document).ready(function (){
    $('.btn-danger').click(function (e) {
        var r = confirm("Are you sure!");
              if (r == true) {

              }
              else
              {
                e.preventDefault();
              }

    });

});

</script>
{% endblock %}

BookMyDoc/templates/hospital/doc_list.html
{% extends 'base.html' %}
{% block title %}All doctor list page{% endblock %}
{% block content %}
{% include 'partials/messages.html' %}

<div class="container">
    <div class="page-header">
        <center><h2>
            Doctor List
        </h2></center>
    </div>

    <table class="responstable">
        <tr>
            <th>Name</th>
            <th>Specialization</th>
            <th>Council</th>
            <th>Action</th>
        </tr>
        {% for all_doc in all_doc %}

        <tr>
            <td>Dr. {{all_doc.user.first_name|title}} {{all_doc.user.last_name|title}}</td>
            <td>{{all_doc.specialization}}</td>
            <td>{{all_doc.council}}</td>
            <td><a href="{%url 'hospital:delete_doc' all_doc.id%}" class="btn btn-danger">Delete</a></td>
        </tr>
        {% endfor %}

    </table>
</div>


{% endblock %}
{% block js %}
{% endblock %}

BookMyDoc/templates/hospital/hospital_dashboard.html
{% extends 'base.html' %}
{% block title %}Doctor Dashboard Page{% endblock %}
{% block content %}
{% include 'partials/messages.html' %}
<div class="container">
    <div class="page-header">
        <center><h2>
            Dashboard
        </h2></center>
    </div>
    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'hospital:hospital_profile' request.user.id %}">
            <div class="card text-white mb-3" style="max-width: 16rem; background: #28a745eb;">
                <!--  <div class="card-header">Appointments</div>-->
                <div class="card-body">
                    <h4 class="card-title">Hospital Profile</h4>
                    <div class="rotate">
                        <i class="fa fa-user fa-3x"></i>
                    </div>

                    <p class="card-text-right"></p>
                </div>
            </div>
                </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'hospital:doc_list' %}">
            <div class="card text-white mb-3" style="max-width: 16rem; background: #17a2b8;">
                <!--  <div class="card-header">Appointments</div>-->
                <div class="card-body">
                    <h4 class="card-title">All Doctors</h4>
                    <div class="rotate">
                        <i class="fa fa-list-alt fa-3x"></i>
                    </div>

                    <p class="card-text-right"></p>
                </div>
            </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'hospital:add_doctor' %}">
                <div class="card text-white mb-3" style="max-width: 16rem; background: #ff2489e0;">
                    <!--  <div class="card-header">Appointments</div>-->
                    <div class="card-body">
                        <h4 class="card-title">Add Doctors</h4>
                        <div class="rotate">
                            <i class="fa fa-user-md fa-3x"></i>
                        </div>

                        <p class="card-text-right"></p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4">
            <a id="hospital_image">
                <div class="card text-white mb-3" style="max-width: 16rem; background: #ff5e00;">
                    <!--  <div class="card-header">Appointments</div>-->
                    <div class="card-body">
                        <h4 class="card-title">Add Images</h4>
                        <div class="rotate">
                            <i class="fa fa-picture-o fa-3x"></i>
                        </div>

                        <p class="card-text-right"></p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'doctor:all_hospital' %}">
                <div class="card text-white mb-3" style="max-width: 16rem; background: #8500ffc7;">
                    <!--  <div class="card-header">Appointments</div>-->
                    <div class="card-body">
                        <h4 class="card-title">All Hospital</h4>
                        <div class="rotate">
                            <i class="fa fa-hospital-o fa-3x"></i>
                        </div>

                        <p class="card-text-right"></p>
                    </div>
                </div>
            </a>
        </div>
                <div class="col-md-4">
            <a href="{% url 'hospital:all_doctor_list' %}">
                <div class="card text-white mb-3" style="max-width: 16rem; background: #ff8d00d6;">
                    <!--  <div class="card-header">Appointments</div>-->
                    <div class="card-body">
                        <h4 class="card-title">Doctor List</h4>
                        <div class="rotate">
                            <i class="fa fa-th-list fa-3x"></i>
                            <div align="right">
                                <span class="badge badge-danger ml-3" style="font-size: 17px;">{{other_appointment_list.count}}</span>
                            </div>
                        </div>

                        <p class="card-text-right"></p>
                    </div>
                </div>
            </a>
        </div>


    </div>


</div>
</div>
<div class="modal fade" id="modal-image">
    <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>
</div>





{% endblock %}
{% block js %}
<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
        }
    }
});

$(document).ready(function() {
    $('#hospital_image').click(function() {
         var url = "{% url 'hospital:upload_hospital_images' %}";
         $.ajax({
             url:  url,
             type : 'get',

             success: function(data) {
                $("#modal-image").modal("show");

                $("#modal-image .modal-content").html(data.html_form);
             },
             error: function(data) {
                console.log(data);
             }
        });

    });

  $("#modal-image").on("submit", ".hospital_image", function (e) {
<!--    e.preventDefault();-->
    var form = $(this);
    var formData = new FormData(this);
    $.ajax({
      url: form.attr("action"),
      data: formData,
      type: form.attr("method"),
      success: function (data) {

        if (data.form_is_valid) {
          $("#modal-image").modal("hide");
          location.reload();
        }
        else {
          $("#modal-image .modal-content").html(data.html_form);
        }
      },
       cache: false,
       contentType: false,
       processData: false
    });
    return false;
  });

});
</script>
{% endblock %}

BookMyDoc/templates/hospital/hospital_profile.html
{% extends 'base.html' %}
{% block title %} Hospital Profile Page {% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="page-header">
        <center><h2>
            Hospital Profile
        </h2></center>
    </div>
    <div class="row" style="color: black;">
        <div class="col-md-8">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form|crispy }}

                {{ form|crispy }}
                <input type="submit" value="submit" class="btn btn-primary">
                <input type="reset" value="clear" class="btn btn-success">
            </form>
        </div>
    </div>
</div>

{% endblock content %}

BookMyDoc/templates/hospital/upload_images.html
{% load crispy_forms_tags %}
<form method="post" action="{% url 'hospital:upload_hospital_images' %}" enctype="multipart/form-data"
      class="hospital_image">
    {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Add hospital image</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {{ form|crispy }}

        <button type="submit" class="btn btn-sm btn-primary">Submit</button>
        <button type="reset" class="btn btn-sm btn-success">Clear</button>
    </div>
    <div class="options text-right">
        <a href="{% url 'hospital:all_hospital_images' %}" style="margin: 5px;" class="btn btn-info">See all images</a>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
    </div>
</form>